# Welcome to Python!

## Numerics  
Types are inferred in python.  Variables can be overwritten, and types can be reassigned.

In [1]:
x = 3
print type(x)

<type 'int'>


In [2]:
x = 3.0 # re-assign to a different type
print str(type(x))
print type(int(x))

<type 'float'>
<type 'int'>


Floats and ints are immutable

In [3]:
x = 4.0
y = x
print x
y += 2
print x
print y

4.0
4.0
6.0


## Lists

In [5]:
some_list = [1,2,3] # a list of ints
print "The list is %s" % some_list
print "The length of the list is %s" % len(some_list)
print "The type of some_list is %s" % type(some_list)

The list is [1, 2, 3]
The length of the list is 3
The type of some_list is <type 'list'>


Lists are mutable (this is actually an example of copying by reference...we'll talk about this tomorrow)

In [6]:
x = [1, 2]
y = x
y.append(3)
print x

[1, 2, 3]


Lists can be composed of whatever you want!

In [7]:
some_list.append("a string")
print some_list
some_list.append(['a', 'b', 'c'])
print some_list

[1, 2, 3, 'a string']
[1, 2, 3, 'a string', ['a', 'b', 'c']]


In [8]:
another_list = range(10)
print another_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
# indexing lists
print another_list[0]
print another_list[-1]
print another_list[2:5]

0
9
[2, 3, 4]


Check for a value in a list using the "in" keyword

In [15]:
print 1 in another_list
print -10 in another_list

True
False


In [43]:
# remove an element
another_list.pop()
print another_list

[0, 1, 2, 3, 4, 5, 6, 7]


In [44]:
# concatenate lists
print [1, 2] + [3, 4]

[1, 2, 3, 4]


List comprehensions make code more concise

In [18]:
print [x*2 for x in another_list]
print [x for x in another_list if x % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8]


Map, filter, and reduce can use lambda functions

In [20]:
print another_list
print map(lambda x: x*2, another_list)
print filter(lambda x: x % 2 == 0, another_list)
print reduce(lambda x, y: x+y, another_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 2, 4, 6, 8, 10, 12, 14, 16]
[0, 2, 4, 6, 8]
36


In [11]:
from itertools import chain, imap
def flatmap(f, items):
    return chain.from_iterable(imap(f, items))
list_of_lists = [range(3) for x in xrange(3)]
print list_of_lists
print list(flatmap(lambda x: x, list_of_lists))

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]
[0, 1, 2, 0, 1, 2, 0, 1, 2]


Range creates a list while xrange is an iterator

In [47]:
print range(5)
print xrange(5)
print list(xrange(5))
for i in xrange(5):
    print i

[0, 1, 2, 3, 4]
xrange(5)
[0, 1, 2, 3, 4]
0
1
2
3
4


## Sets

In [13]:
some_set = {1, 2, 3}
print some_set

print dir(some_set)

set([1, 2, 3])
['__and__', '__class__', '__cmp__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__iand__', '__init__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [14]:
print 1 in some_set
print -10 in some_set

True
False


In [15]:
some_set.add(1)
print some_set
some_set.add(4)
print some_set

set([1, 2, 3])
set([1, 2, 3, 4])


**Sets are mutable**

In [34]:
x = {1,2}
y = x
y.add(3)
print x

set([1, 2, 3])


In [17]:
# cannot index a set because it has no order
some_set[1]

TypeError: 'set' object does not support indexing

## Dictionaries

In [21]:
some_dict = {'a': 0, 'b': 1, 'c': 2}
print some_dict['a']
print some_dict.get('a')
print some_dict.get('d')
# compare to error in key lookup
print some_dict['d']

0
0
None


KeyError: 'd'

In [45]:
some_dict['list'] = ['a', 1, 2.0]
print some_dict

{'a': 0, 'c': 2, 'b': 1, 'list': ['a', 1, 2.0]}


**Dictionaries are mutable**

In [36]:
x = {'a': 0}
y = x
y['b'] = 1
print x

{'a': 0, 'b': 1}


In [37]:
# loop over the keys in a dict
for key in some_dict:
    print key, some_dict[key]

a 0
c 2
b 1


In [39]:
for key, val in some_dict.iteritems():
    print key, val

a 0
c 2
b 1


## Strings

In [7]:
a = "hello"
b = "world"
print a + " " + b

hello world


**You can index strings like lists**

In [8]:
print a[0]
print a[1:]

h
ello


In [9]:
# split and join strings
fruits = "apple, orange, banana, mango"
list_of_fruits = fruits.split(',')
print list_of_fruits
print ", ".join(list_of_fruits)

['apple', ' orange', ' banana', ' mango']
apple,  orange,  banana,  mango


In [10]:
# string formatting
x = 4
pi = 3.14
print "x = %d and pi = %1.2f" % (x, pi)

x = 4 and pi = 3.14


In [11]:
# strings can be looped over like lists
for char in a:
    print char,

h e l l o


In [12]:
list(a)

['h', 'e', 'l', 'l', 'o']

In [13]:
set(a)

{'e', 'h', 'l', 'o'}

## Tuples

In [36]:
some_tuple = (1, 2)
print some_tuple[0]

1


**Tuples are immutable**

In [22]:
a=[1,2,3,4]
a_tup=tuple(a)
print 'array operations: \n' + dir(a).__str__()
print 
print 'tuple operations: \n' + dir(a_tup).__str__()

array operations: 
['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__delslice__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__setslice__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']

tuple operations: 
['__add__', '__class__', '__contains__', '__delattr__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getslice__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'coun

## Numpy

In [4]:
import numpy as np

In [5]:
python_list = range(100000)
numpy_array = np.arange(100000)
print type(numpy_array), type(python_list)

<type 'numpy.ndarray'> <type 'list'>


In [6]:
%timeit square = map(lambda x: x*x, python_list)

100 loops, best of 3: 20.6 ms per loop


In [7]:
%timeit square = numpy_array*numpy_array

The slowest run took 42.21 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 50.7 µs per loop


In [7]:
A = np.random.randint(0, 9, size=(3,3))
print "Matrix\n", A
print "Transpose\n", A.T

Matrix
[[3 2 1]
 [5 1 1]
 [7 4 5]]
Transpose
[[3 5 7]
 [2 1 4]
 [1 1 5]]


#### Matrix Multiplication

The product C of two matrices A and B is defined as:

$$C_{i,k}=\sum_{j=1}^{N} A_{i,j}B_{j,k}$$

<img src="MatrixMult.png">

In [8]:
def multiply(A, B):
    rows = len(A[0])
    cols = len(B)
    C = [[0]*cols for i in xrange(rows)]
    # iterate through rows of X
    for i in range(len(A)):
       # iterate through columns of Y
       for j in range(len(B[0])):
           # iterate through rows of Y
           for k in range(len(B)):
               C[i][j] += A[i][k] * B[k][j]
    return C

In [9]:
A = np.random.randint(0, 100*100, (100, 100))
A_list = A.tolist()

**Timing for different ways to multiply matrices**

In [10]:
# pure Python
%timeit multiply(A_list, A_list)

1 loop, best of 3: 459 ms per loop


In [11]:
# Numpy array
%timeit np.dot(A, A)

1000 loops, best of 3: 670 µs per loop


In [77]:
# Numpy matrix
A_mat = np.mat(A)
%timeit A_mat*A_mat

1000 loops, best of 3: 747 µs per loop


## Looping

In [42]:
fruits = ['apple', 'orange', 'banana']
for idx, fruit in enumerate(fruits):
    print "fruits[%d] = %s" % (idx, fruit)

fruits[0] = apple
fruits[1] = orange
fruits[2] = banana


In [43]:
colors = ['red', 'orange', 'yellow']
fruits_and_colors = zip(fruits, colors)
for fruit, color in fruits_and_colors:
    print "%s is %s" % (fruit, color)

apple is red
orange is orange
banana is yellow


In [51]:
%timeit [num for num in range(0, 100000000, 50)]

10 loops, best of 3: 113 ms per loop


In [52]:
%timeit [num for num in xrange(0, 100000000, 50)]

10 loops, best of 3: 85.9 ms per loop


## Functions

In [53]:
def myfunc(x):
    return x*x
def mymap(f, items):
    return [f(x) for x in items]

In [54]:
print mymap(myfunc, range(5))

[0, 1, 4, 9, 16]
